[build-system]
requires = ["tqdm"]
build-backend = "flit_core.buildapi"

[project]
name = "AEMETScrapper"
authors = [{name = "Daniel Enériz", email = "eneriz@unizar.es"}]
dynamic = ["0.1", "A simple AEMET OpenData API scrapper"]
